package model;
// Generated 14-sep-2022 9:24:10 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String cliId;
     private String cliApellidos;
     private String cliNombres;
     private String cliNombrCompleto;
     private String cliDireccion;
     private String cliCiudad;
     private String cliTelefono;

    public Clientes() {
    }

	
    public Clientes(String cliId) {
        this.cliId = cliId;
    }
    public Clientes(String cliId, String cliApellidos, String cliNombres, String cliNombrCompleto, String cliDireccion, String cliCiudad, String cliTelefono) {
       this.cliId = cliId;
       this.cliApellidos = cliApellidos;
       this.cliNombres = cliNombres;
       this.cliNombrCompleto = cliNombrCompleto;
       this.cliDireccion = cliDireccion;
       this.cliCiudad = cliCiudad;
       this.cliTelefono = cliTelefono;
    }
   
    public String getCliId() {
        return this.cliId;
    }
    
    public void setCliId(String cliId) {
        this.cliId = cliId;
    }
    public String getCliApellidos() {
        return this.cliApellidos;
    }
    
    public void setCliApellidos(String cliApellidos) {
        this.cliApellidos = cliApellidos;
    }
    public String getCliNombres() {
        return this.cliNombres;
    }
    
    public void setCliNombres(String cliNombres) {
        this.cliNombres = cliNombres;
    }
    public String getCliNombrCompleto() {
        return this.cliNombrCompleto;
    }
    
    public void setCliNombrCompleto(String cliNombrCompleto) {
        this.cliNombrCompleto = cliNombrCompleto;
    }
    public String getCliDireccion() {
        return this.cliDireccion;
    }
    
    public void setCliDireccion(String cliDireccion) {
        this.cliDireccion = cliDireccion;
    }
    public String getCliCiudad() {
        return this.cliCiudad;
    }
    
    public void setCliCiudad(String cliCiudad) {
        this.cliCiudad = cliCiudad;
    }
    public String getCliTelefono() {
        return this.cliTelefono;
    }
    
    public void setCliTelefono(String cliTelefono) {
        this.cliTelefono = cliTelefono;
    }




}


